### ISSUE TITLE
Adding json tags to the public structs

### ISSUE THREAD

**Issue by shmul** [digineo/go-ping#7]
Hi,

Thanks for this neat tool. Would you mind adding json tags to the public structs (`monitor.Metrics` is what I'm particularly after)?

Cheers,
Shmul

**Comment by corny** [comment]
Well, all fields of `monitor.Metrics` are exported. So it's easy to marshal it to JSON.

**Comment by shmul** [comment]
Yep, you are right of course. Just had lowercase field names in mind :)

**Comment by corny** [comment]
Since there is no standard for naming keys in JSON I want to stay with the Go defaults.

I see two options for you:
* Using [easyjson](https://github.com/mailru/easyjson) that has options for using CamelCase/snake_case
* Clone the `monitor.Metrics` and add your JSON tags: https://stackoverflow.com/a/46979561
